# Try to find tinyxml
# Based upon FindBZip2 which is included in cmake 2.6


FIND_PATH(TINYXML_INCLUDE_DIR tinyxml.h)
FIND_LIBRARY(TINYXML_LIBRARY NAMES tinyxml)
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TinyXML DEFAULT_MSG TINYXML_LIBRARY TINYXML_INCLUDE_DIR)

MARK_AS_ADVANCED(TINYXML_INCLUDE_DIR TINYXML_LIBRARY)
